### ISSUE TITLE
Add on stopped working

### ISSUE THREAD

**Issue by ekkesa** [giuseppecastaldo/ha-addons#32]
Hi,

This was working very well, but stopped working on Friday morning (23/06/02). The log shows no errors, it just never reaches client ready status. I can see that _node index_ is running and consuming resources on the host machine, but it just never finishes the start up.

I tried adding a second client, when scanning the QR code I got an error stating that the QR code in invalid, and I must ensure that it is from WA web, Desktop or other authorised app. Perhaps they changed something on their side which broke the add-on?

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[01:02:21] INFO: Installed custom component.
[2023-06-11T01:02:23.221] [INFO] default - Whatsapp Addon started.
```

**Comment by Caldin-Maldin** [comment]
I confirm. A similar problem with the inability to add a device via a qr code. HA 2023.6

**Comment by yazend** [comment]
Same here, whatsapp addon are not länger sending message, I reinsalled the addon as well, now not posible to connect via QR code, ( always get the message... please try later error occured )

**Comment by ekkesa** [comment]
> a possible fix it to update the version on src/Defaults/baileys-version.json to "version": [2, 2323, 4] but i do not use HA supervised so cannot test this

I made a fork and did the change there - It seemed to have resolved the issue. The fork is https://github.com/ekkesa/ha-addons - I will delete the fork once this repo is updated.

**Comment by ekkesa** [comment]
Might have spoken to soon - It seems to resolve the QR code issue and the client not connecting, but it seems to fail on sending messages.

**Comment by Begie1605** [comment]
How can i install your fork in HA? i have it running now as addon but don't seem to be able to install it from your fork....

**Comment by ekkesa** [comment]
Same method as the original - Just add my repo to HA and install. Remember to stop/remove the original one beforehand.

**Comment by Begie1605** [comment]
ok thnx for the answer....but if i add your repository (https://github.com/ekkesa/ha-addons) i get the other one in my overvies? Is this normal (i removed the original repositories..)
![image](https://github.com/giuseppecastaldo/ha-addons/assets/76470558/5d5ab3c3-ea24-452f-9932-9d95073439f2)

**Comment by ekkesa** [comment]
Correct - The labelling and all stayed the same - I didn't bother with it as it is only temporary till the original is fixed.

**Comment by matteoopc** [comment]
It's not the same for me. I get error when I scan qr...

**Comment by scorbacella** [comment]
> Same method as the original - Just add my repo to HA and install. Remember to stop/remove the original one beforehand.

Hi I tried to run your fork but the QRcode still doesn't appear.
Can you help me?

Thanks
